#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod aavelooper;
pub mod address;
pub mod context;
pub mod erc20;
pub mod datatypes;
pub mod iaaveincentivescontroller;
pub mod iaavepriceoracle;
pub mod ilendingpool;
pub mod ilendingpooladdressesprovider;
pub mod istakedaave;
pub mod ierc20;
pub mod ierc20metadata;
pub mod ierc20permit;
pub mod immutableownable;
pub mod safeerc20;
pub mod ierc1155errors;
pub mod ierc20errors;
pub mod ierc721errors;
